package practicabuscaminas;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Grupo G
 */
public class VentanaAdmin extends javax.swing.JFrame {

    private Almacen_partidas almacenPartidas = new Almacen_partidas();
    private Administrador admin;
    private File archivoJugadores;
    private File archivoPartidas;

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        jfc.addChoosableFileFilter(new FileNameExtensionFilter("*.txt", "txt"));
        nombreTextField1.setBackground(new java.awt.Color(0, 0, 0, 1));
        contrasenaTextField2.setBackground(new java.awt.Color(0, 0, 0, 1));
        jTextField3.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.setTitle("Admin ");
        admin = new Administrador("root", "root");
        archivoJugadores = new File("jugadores.dat");
        archivoPartidas = new File("partidas.dat");

        try {
            admin.cargaListadoB(archivoJugadores);

        } catch (Exception e) {
            e.getMessage();
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfc = new javax.swing.JFileChooser();
        jSeparator3 = new javax.swing.JSeparator();
        nombreTextField1 = new javax.swing.JTextField();
        contrasenaTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registrarseButton1 = new javax.swing.JButton();
        darBajaButton2 = new javax.swing.JButton();
        cerrarSesionButton6 = new javax.swing.JButton();
        clearButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        crearTxtButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        verPartidaButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        nombreTextField1.setBorder(null);

        contrasenaTextField2.setBorder(null);
        contrasenaTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Contraseña");

        registrarseButton1.setBackground(new java.awt.Color(0, 153, 255));
        registrarseButton1.setForeground(new java.awt.Color(255, 255, 255));
        registrarseButton1.setText("Registrarse");
        registrarseButton1.setBorder(null);
        registrarseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseButton1ActionPerformed(evt);
            }
        });

        darBajaButton2.setBackground(new java.awt.Color(0, 153, 255));
        darBajaButton2.setForeground(new java.awt.Color(255, 255, 255));
        darBajaButton2.setText("Darse de baja");
        darBajaButton2.setBorder(null);
        darBajaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darBajaButton2ActionPerformed(evt);
            }
        });

        cerrarSesionButton6.setBackground(new java.awt.Color(0, 153, 255));
        cerrarSesionButton6.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionButton6.setText("Cerrar sesión");
        cerrarSesionButton6.setBorder(null);
        cerrarSesionButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionButton6ActionPerformed(evt);
            }
        });

        clearButton5.setBackground(new java.awt.Color(0, 153, 255));
        clearButton5.setForeground(new java.awt.Color(255, 255, 255));
        clearButton5.setText("Clear");
        clearButton5.setBorder(null);
        clearButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton5ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        crearTxtButton3.setBackground(new java.awt.Color(0, 153, 255));
        crearTxtButton3.setForeground(new java.awt.Color(255, 255, 255));
        crearTxtButton3.setText("Leer Ultima Partida TXT");
        crearTxtButton3.setBorder(null);
        crearTxtButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTxtButton3ActionPerformed(evt);
            }
        });

        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("INORMACIÓN SOBRE PARTIDAS");

        verPartidaButton4.setBackground(new java.awt.Color(0, 153, 255));
        verPartidaButton4.setForeground(new java.awt.Color(255, 255, 255));
        verPartidaButton4.setText("Ver partida");
        verPartidaButton4.setBorder(null);
        verPartidaButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPartidaButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cargar Listado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        jMenuItem2.setText("Mostrar Listado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clearButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2)
                                    .addGap(44, 44, 44)
                                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(contrasenaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(registrarseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(darBajaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(crearTxtButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(verPartidaButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(54, 54, 54)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(cerrarSesionButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(contrasenaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registrarseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(darBajaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verPartidaButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crearTxtButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(cerrarSesionButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        new VentanaLogin().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void contrasenaTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaTextField2ActionPerformed

    private void registrarseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseButton1ActionPerformed
        String nombre = nombreTextField1.getText();
        String contrasenia = contrasenaTextField2.getText();
        Jugador jug = new Jugador(nombre, contrasenia);

        if ("".equals(jug.getNombre()) || "".equals(jug.getContrasena())) {
            jTextArea1.append("Usuario no válido");
            nombreTextField1.setText("");
            contrasenaTextField2.setText("");

        } else if (!admin.autenticar(jug)) {
            admin.alta(jug);
            jTextArea1.append("Jugador: " + nombre + " añadido correctamente\n");

        } else {
            jTextArea1.append("El jugador ya esta en dado de alta\n");

        }
        nombreTextField1.setText("");
        contrasenaTextField2.setText("");
    }//GEN-LAST:event_registrarseButton1ActionPerformed

    private void darBajaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darBajaButton2ActionPerformed

        String nombre = nombreTextField1.getText();
        String contrasenia = contrasenaTextField2.getText();
        Jugador jug = new Jugador(nombre, contrasenia);

        if ("".equals(jug.getNombre()) || "".equals(jug.getContrasena())) {
            jTextArea1.append("Usuario no válido");
            nombreTextField1.setText("");
            contrasenaTextField2.setText("");

        } else if (admin.autenticar(jug)) {
            admin.baja(jug);
            jTextArea1.append("Jugador: " + nombre + " ha sido dado de baja\n");

        } else {
            jTextArea1.append("El jugador aún no esta registrado\n");

        }
        nombreTextField1.setText("");
        contrasenaTextField2.setText("");

    }//GEN-LAST:event_darBajaButton2ActionPerformed

    private void cerrarSesionButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionButton6ActionPerformed
        try {
            admin.guardarListadoB(archivoJugadores);

        } catch (IOException e) {
            e.printStackTrace();  // Imprimir la traza completa de la excepción
        }
        this.dispose();
        new VentanaLogin().setVisible(true);


    }//GEN-LAST:event_cerrarSesionButton6ActionPerformed

    private void clearButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton5ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_clearButton5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jTextArea1.append(admin.listado());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File selectedFile = null;
        int returnValue = jfc.showOpenDialog(null);

        try {
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                selectedFile = jfc.getSelectedFile();
            }
            admin.cargaListado(selectedFile);
            jTextArea1.append("Archivo cargado\n");

        } catch (IOException e) {
            jTextArea1.append("ERROR E/S\n");
        } catch (NullPointerException n) {

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void crearTxtButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTxtButton3ActionPerformed
        try (BufferedReader entrada = new BufferedReader(new FileReader(new File("infopartida.txt")))) {
            String linea;

            while ((linea = entrada.readLine()) != null) {
                jTextArea1.append(linea + "\n");
            }
        } catch (FileNotFoundException e) {
            jTextArea1.append("Error: Archivo no encontrado");
            e.printStackTrace();
        } catch (IOException e) {
            System.err.println("Error E/S");
            e.printStackTrace();
        }

    }//GEN-LAST:event_crearTxtButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void verPartidaButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPartidaButton4ActionPerformed
        try {
            // TODO add your handling code here:
            almacenPartidas.cargaListadoB(archivoPartidas);
        } catch (Exception ex) {
            Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextArea1.setText("");
        ArrayList<Partida> partidas = almacenPartidas.getPartidas();
        int i = partidas.indexOf(Integer.valueOf(jTextField3.getText()));
        Partida partida = partidas.get(i);
        jTextArea1.append(partida.infoPartida());
    }//GEN-LAST:event_verPartidaButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionButton6;
    private javax.swing.JButton clearButton5;
    private javax.swing.JTextField contrasenaTextField2;
    private javax.swing.JButton crearTxtButton3;
    private javax.swing.JButton darBajaButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JFileChooser jfc;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JButton registrarseButton1;
    private javax.swing.JButton verPartidaButton4;
    // End of variables declaration//GEN-END:variables
}
