package practicabuscaminas;

import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Grupo G
 */
public class VentanaUser extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUser
     */
    VentanaJugar ventanaJugar;
    Almacen_Usuario alm;
    File archivo;
    private Jugador jugador;

    public VentanaUser() {
        initComponents();
        alm = new Almacen_Usuario();
        archivo = new File("jugadores.dat");
        ventanaJugar = new VentanaJugar();

        try {
            alm.cargaListadoB(archivo);

        } catch (Exception e) {
            jTextArea1.append("ERROR E/S\n");
        }
    }

    public void setJugador(Jugador j) {
        this.jugador = j;
        jLabel1.setText("Jugador: " + jugador.getNombre());
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        verClasificacion = new javax.swing.JButton();
        verEstadisticas = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        verClasificacion1 = new javax.swing.JButton();
        verEstadisticas1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        clearMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        verClasificacion.setBackground(new java.awt.Color(0, 153, 255));
        verClasificacion.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        verClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        verClasificacion.setText("Ver clasificación Victorias");
        verClasificacion.setBorder(null);
        verClasificacion.setBorderPainted(false);
        verClasificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClasificacionActionPerformed(evt);
            }
        });

        verEstadisticas.setBackground(new java.awt.Color(0, 153, 255));
        verEstadisticas.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        verEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        verEstadisticas.setText("Ver estadísticas");
        verEstadisticas.setBorder(null);
        verEstadisticas.setBorderPainted(false);
        verEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstadisticasActionPerformed(evt);
            }
        });

        jugar.setBackground(new java.awt.Color(0, 153, 255));
        jugar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jugar.setForeground(new java.awt.Color(255, 255, 255));
        jugar.setText("Jugar");
        jugar.setBorder(null);
        jugar.setBorderPainted(false);
        jugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Menú del Jugador");

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        verClasificacion1.setBackground(new java.awt.Color(0, 153, 255));
        verClasificacion1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        verClasificacion1.setForeground(new java.awt.Color(255, 255, 255));
        verClasificacion1.setText("Ver clasificación Nombre");
        verClasificacion1.setBorder(null);
        verClasificacion1.setBorderPainted(false);
        verClasificacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verClasificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClasificacion1ActionPerformed(evt);
            }
        });

        verEstadisticas1.setBackground(new java.awt.Color(0, 153, 255));
        verEstadisticas1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        verEstadisticas1.setForeground(new java.awt.Color(255, 255, 255));
        verEstadisticas1.setText("Ver estadísticas Rivales");
        verEstadisticas1.setBorder(null);
        verEstadisticas1.setBorderPainted(false);
        verEstadisticas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verEstadisticas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstadisticas1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Herramientas");

        clearMenuItem1.setText("Limpiar cuadro de texto");
        clearMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(clearMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(verEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(verEstadisticas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verClasificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verClasificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(verEstadisticas1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new VentanaLogin().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        ventanaJugar.setJugador(jugador);
        ventanaJugar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jugarActionPerformed

    private void verEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstadisticasActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        ArrayList<Jugador> jugadores = alm.getJugadores();
        int i = jugadores.indexOf(jugador);
        jugador = jugadores.get(i);
        jTextArea1.append(jugador.getEstadisticaJugador().toString());
    }//GEN-LAST:event_verEstadisticasActionPerformed

    private void clearMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItem1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_clearMenuItem1ActionPerformed

    private void verClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClasificacionActionPerformed
        jTextArea1.setText("");
        ArrayList<Jugador> Clasevictorias = alm.clasificacion_por_victorias();
        String resultadoVictorias = alm.listadoClasificacion(Clasevictorias);
        jTextArea1.append(resultadoVictorias);
    }//GEN-LAST:event_verClasificacionActionPerformed

    private void verClasificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClasificacion1ActionPerformed
        jTextArea1.setText("");
        ArrayList<Jugador> ClasiNombres = alm.clasificacion_por_nombre();
        String resultadoNombres = alm.listadoClasificacion(ClasiNombres);
        jTextArea1.append(resultadoNombres);
    }//GEN-LAST:event_verClasificacion1ActionPerformed

    private void verEstadisticas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstadisticas1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        ArrayList<Cara_a_cara> rivales = jugador.getRivales();
        Iterator<Cara_a_cara> i = rivales.iterator();

        while (i.hasNext()) {
            jTextArea1.append(i.next().toString());
        }
    }//GEN-LAST:event_verEstadisticas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clearMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jugar;
    private javax.swing.JButton verClasificacion;
    private javax.swing.JButton verClasificacion1;
    private javax.swing.JButton verEstadisticas;
    private javax.swing.JButton verEstadisticas1;
    // End of variables declaration//GEN-END:variables
}
